# Generated by Django 4.2.27 on 2025-12-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='活動名稱')),
                ('end_date', models.CharField(max_length=50, verbose_name='活動結束日期')),
                ('location', models.CharField(max_length=100, verbose_name='地點')),
                ('description', models.TextField(verbose_name='描述')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='圖片網址')),
                ('activity_link', models.TextField(blank=True, null=True, verbose_name='活動連結')),
            ],
            options={
                'verbose_name': '活動',
                'verbose_name_plural': '活動列表',
            },
        ),
    ]
